sudo: true
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gobject-introspection
  - sudo apt-get install python-dbus python3-dbus

install:
  - travis_retry pip install tox

script:
  - tox
